# .github/workflows/update-number.yml

name: Update Number

on:
  schedule:
    # Runs every day at 12:00 PM UTC
    - cron: '0 12 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update_job:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checks out your repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Reads, increments, and writes the new number
      - name: Update the number
        run: |
          current_number=$(cat number.txt)
          new_number=$((current_number + 1))
          echo $new_number > number.txt

      # 3. Commits and pushes the change under your name 👤
      - name: Commit and push changes
        run: |
          # IMPORTANT: Replace with your details
          git config --global user.name 'mayur-dhavan'
          git config --global user.email 'mayurdhavan2244@gmail.com'
          
          git add number.txt
          git commit -m "Update number to $(cat number.txt)"
          git push